  <hr />
  <ul class="socialnetwork">
    <li><strong>SHARE:</strong></li>
    <li class="fb"><div class="fb-like" data-href="https://www.facebook.com/Somali.Taekwondo.Official" data-send="false" data-layout="button_count" data-width="450" data-show-faces="true"></div></li>
    <li><div class="g-plusone" data-size="medium" data-href="https://plus.google.com/b/105164102392878483908/105164102392878483908/"></div></li>
    <li><a href="https://twitter.com/SomaliTaekwondo" class="twitter-follow-button" data-dnt="true">Follow @twitterapi</a></li>
  </ul>
  <br class="all" />
  <hr />
  <br class="all" />
  <div class="fb-comments" data-href="<?php echo curPageURL(); ?>" data-width="470" data-num-posts="10"></div>
